### ISSUE TITLE
Accessibility testing - Sim Daltonism

### ISSUE THREAD

**Issue by karenhodgkinson** [libecap/ecommerce-pattern-library#6]
LOVED your website!! Sim Daltonism testing went well, only issues being for people with monochromatic colour blindness. The navigation links don't change enough to indicate when active/hover vs inactive (see screenshot 1). Only for monochromatic colour blindness, every other type of colour blindness it was good! The main page banner with the shop name was also difficult to see for people with monochromatic colour blindness (see screenshot 2
<img width="483" alt="screenshot1" src="https://user-images.githubusercontent.com/31959335/56228659-35e9c200-6046-11e9-8c32-f8c93f656cac.png">
<img width="640" alt="screenshot2" src="https://user-images.githubusercontent.com/31959335/56228660-35e9c200-6046-11e9-8798-4633a267862e.png">

).

**Comment by libecap** [comment]
Thanks! Ill try and see if I can fix this
